name: ci
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: cache dependencies maven
        uses: actions/cache@v1
        with: 
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Install java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '11'
      
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
           maven-version: 3.8.2
      
        - name: BUild project
          if: github.event_name == 'push'
          run: #comando para build no projeto